### PR TITLE
add security message

### PR DESCRIPTION
**Pull request by jdsmithit**
add a security message to the platform

### CODE REVIEW

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

# CodeScene PR Check
---
**View detailed results** in [CodeScene](https://codescene.dfds.cloud/32/delta-analysis/view/da67f576201d9c83ecf47c6b4860ed04e27e1a28)

|||
| --- | ---- |
| **Quality Gates** |OK|
| **Recommended Review Level** |Detailed -- Increased risk for defects: The risk is higher as much of the code in this repo (99% of all commits) is written by other authors.|


## No Warnings


---

**Review by jandr-dfds — APPROVED** [review]

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

# CodeScene PR Check
---
**View detailed results** in [CodeScene](https://codescene.dfds.cloud/32/delta-analysis/view/c0cd8b808f0cfbf2efda5ae3e26478dd351b95a5)

|||
| --- | ---- |
| **Quality Gates** |OK|
| **Recommended Review Level** |Detailed -- Increased risk for defects: The change involves more modules than 69% of the historic high-risk change sets. The risk is higher as much of the code in this repo (99% of all commits) is written by other authors.|


## No Warnings


---

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

# CodeScene PR Check
---
**View detailed results** in [CodeScene](https://codescene.dfds.cloud/32/delta-analysis/view/05717022cc2d5c2f76f2c89f166b88fac41332a1)

|||
| --- | ---- |
| **Quality Gates** |OK|
| **Recommended Review Level** |Detailed -- Increased risk for defects: The change involves more modules than 78% of the historic high-risk change sets. The risk is higher as much of the code in this repo (99% of all commits) is written by other authors.|


## No Warnings


---

**Review by SEQUOIIA — APPROVED** [review]
Seems reasonable!

**Pull request merged**
