### PR TITLE
remove countdown

### PR DESCRIPTION
**Pull request by kim-lindhard-dfds**

### CODE REVIEW

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |1|
| **Quality Gates** |OK|
| **Description** |The change is low risk. No code is modified, only deleted (2) lines of code.|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |3|
| **Quality Gates** |OK|
| **Description** |The change is low risk, and touches 2 files, adds 0 lines of code, and deletes 10 lines. The risk is lower since it is a very experienced author with many contributions.|

**Comment by SEQUOIIA** [comment]
Added an additional commit that makes sure the countdown view component is also removed

image

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |3|
| **Quality Gates** |OK|
| **Description** |The change is low risk, and touches 2 files, adds 0 lines of code, and deletes 10 lines. The risk is lower since it is a very experienced author with many contributions.|

**Pull request merged**
