### PR TITLE
Update TopicAddComponent.js text

### PR DESCRIPTION
**Pull request by kdichev**

### CODE REVIEW

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

# CodeScene Delta Analysis Results

 **View detailed results** in [CodeScene](https://codescene.dfds.cloud/32/delta-analysis/view/f0853892739b5f8fe5f1a10168260e62f71d3cfc)


|||
| --- | ---- |
| **Recommended Review Level** |Detailed -- Increased risk for defects: The risk is higher as much of the code in this repo (99% of all commits) is written by other authors.|

**Review by SEQUOIIA — APPROVED** [review]
I'm fine with this. Perhaps @janwiberg-dfds would be more interested/would like to weigh in regarding the change of wording.

**Comment by janwiberg-dfds** [comment]
Trading accuracy for readability. It's probably fine. I'm a little curious what prompted the change?

**Comment by ZaradarDFDS** [comment]
I prompted the change because quiet frankly I felt the current text was leading towards a single partition pattern with an exemption that didnt quiet cover all the corner cases (e.g. using message keys for semantic partitioning) and granted that it can be very difficult to scale up partitions on existing topics I felt like it was better to change it so we point out that a single partitions can handle a high volume, but if there is any doubt about the "eventing characteristics" of their application we would rather have them reach out to us beforehand so we can help them avoid a situation where they end up having to re-index their topics once it becomes apparent to them that the single partition strategy was not the most desirable srategy for their application

**Comment by kdichev** [comment]
let me know if it[s all good so I can merge this change :)

**Review by ZaradarDFDS — APPROVED** [review]

**Comment by ZaradarDFDS** [comment]
Go ahead and merge it, Jan and I can argue the finer details of partitioning over beers in an hour

**Pull request merged**
